language: cpp
dist: focal

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-10
      - g++-10

install:
  - make get-deps

script:
  - export CC=gcc-10
  - export CXX=g++-10
  - make
  - make test
